const fs = require('fs');

const acl2Questions = [
  // ================= UNIT 1: MY NEW SCHOOL (A Closer Look 2: Present Simple & Adverbs of Frequency) =================
  {
    id: 'q1-acl2-1',
    unitId: 'unit-1',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 1]\\nBa and Phong ________ judo in the school gym every Tuesday afternoon.',
    options: ['do', 'does', 'doing', 'are do'],
    correctAnswer: 'do',
    explanation: 'Chủ ngữ "Ba and Phong" là danh từ số nhiều (2 người), thì Hiện tại đơn giữ nguyên động từ "do".',
    hints: ['Gợi ý 1: "Ba and Phong" là chủ ngữ số ít hay số nhiều?', 'Gợi ý 2: Số nhiều đi với động từ nguyên mẫu.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q1-acl2-2',
    unitId: 'unit-1',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 1]\\nMy new school ________ a large playground and modern science labs.',
    options: ['has', 'have', 'having', 'is has'],
    correctAnswer: 'has',
    explanation: 'Chủ ngữ "My new school" là danh từ số ít, động từ "have" chuyển thành "has" ở thì Hiện tại đơn.',
    hints: ['Gợi ý 1: "My new school" là danh từ số ít.', 'Gợi ý 2: Have chuyển thành has đối với ngôi số ít.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q1-acl2-3',
    unitId: 'unit-1',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 1]\\nThey ________ ride their bicycles to school on rainy days.',
    options: ["don't", "doesn't", "aren't", "not"],
    correctAnswer: "don't",
    explanation: 'Chủ ngữ "They" dùng trợ động từ phủ định "don\'t" + V_inf trong thì Hiện tại đơn.',
    hints: ['Gợi ý 1: "They" đi với don\'t hay doesn\'t?', 'Gợi ý 2: They don\'t + V.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q1-acl2-4',
    unitId: 'unit-1',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 1]\\n________ Vy always do her homework before watching television?',
    options: ['Does', 'Do', 'Is', 'Are'],
    correctAnswer: 'Does',
    explanation: 'Trợ động từ đứng đầu câu hỏi Yes/No với chủ ngữ số ít "Vy" là "Does".',
    hints: ['Gợi ý 1: Chủ ngữ "Vy" là ngôi thứ 3 số ít.', 'Gợi ý 2: Cấu trúc: Does + S + V_inf?'],
    difficulty: 'Trung bình'
  },
  {
    id: 'q1-acl2-5',
    unitId: 'unit-1',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 1]\\nNick is very punctual. He is ________ late for school.',
    options: ['never', 'always', 'usually', 'often'],
    correctAnswer: 'never',
    explanation: '"Punctual" nghĩa là đúng giờ -> Anh ấy KHÔNG BAO GIỜ (never) đi học muộn.',
    hints: ['Gợi ý 1: "Punctual" = đúng giờ.', 'Gợi ý 2: Đúng giờ nghĩa là không bao giờ (never) đi muộn.'],
    difficulty: 'Trung bình'
  },
  {
    id: 'q1-acl2-6',
    unitId: 'unit-1',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 1]\\nHow often ________ your brother play table tennis with his friends?',
    options: ['does', 'do', 'is', 'are'],
    correctAnswer: 'does',
    explanation: 'Câu hỏi "How often" với chủ ngữ số ít "your brother" dùng trợ động từ "does".',
    hints: ['Gợi ý 1: "your brother" số ít.', 'Gợi ý 2: How often + does + S + V?'],
    difficulty: 'Dễ'
  },
  {
    id: 'q1-acl2-7',
    unitId: 'unit-1',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 1]\\nMy mother usually ________ delicious meals for our family after work.',
    options: ['cooks', 'cook', 'cooking', 'is cook'],
    correctAnswer: 'cooks',
    explanation: 'Chủ ngữ số ít "My mother" đi với động từ thêm -s "cooks" ở thì Hiện tại đơn.',
    hints: ['Gợi ý 1: "My mother" là số ít.', 'Gợi ý 2: Động từ "cook" thêm đuôi "-s".'],
    difficulty: 'Dễ'
  },
  {
    id: 'q1-acl2-8',
    unitId: 'unit-1',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 1]\\nWe ________ school uniforms on Mondays and Thursdays.',
    options: ['wear', 'wears', 'wearing', 'are wear'],
    correctAnswer: 'wear',
    explanation: 'Chủ ngữ "We" (chúng tôi) đi với động từ nguyên mẫu "wear".',
    hints: ['Gợi ý 1: "We" là số nhiều.', 'Gợi ý 2: Động từ giữ nguyên.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q1-acl2-9',
    unitId: 'unit-1',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 1]\\nWhich sentence has the correct adverb of frequency position?',
    options: [
      'An usually goes to school on time.',
      'An goes usually to school on time.',
      'Usually An goes to school on time.',
      'An goes to school on time usually.'
    ],
    correctAnswer: 'An usually goes to school on time.',
    explanation: 'Trạng từ chỉ tần suất (usually) đứng TRƯỚC động từ thường (goes).',
    hints: ['Gợi ý 1: Vị trí trạng từ tần suất: đứng trước động từ thường.', 'Gợi ý 2: S + adv + V.'],
    difficulty: 'Trung bình'
  },
  {
    id: 'q1-acl2-10',
    unitId: 'unit-1',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 1]\\n________ you study English lessons on Saturday evenings?',
    options: ['Do', 'Does', 'Are', 'Is'],
    correctAnswer: 'Do',
    explanation: 'Câu hỏi với chủ ngữ "you" dùng trợ động từ "Do".',
    hints: ['Gợi ý 1: "you" đi với trợ động từ "Do".', 'Gợi ý 2: Do + you + V?'],
    difficulty: 'Dễ'
  },

  // ================= UNIT 2: MY HOUSE (A Closer Look 2: Possessive Case & Prepositions of Place) =================
  {
    id: 'q2-acl2-1',
    unitId: 'unit-2',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 2]\\nThis is ________ room. There is a study table and a bookshelf inside.',
    options: ["Elena's", 'Elena', "Elenas'", 'Elena is'],
    correctAnswer: "Elena's",
    explanation: "Sở hữu cách của danh từ riêng Elena là Elena's (Phòng của Elena).",
    hints: ["Gợi ý 1: Thêm 's vào tên riêng.", "Gợi ý 2: Elena's room."],
    difficulty: 'Dễ'
  },
  {
    id: 'q2-acl2-2',
    unitId: 'unit-2',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 2]\\nWhere is the clock? - It is ________ the wall, above the picture.',
    options: ['on', 'in', 'at', 'under'],
    correctAnswer: 'on',
    explanation: 'Giới từ "on the wall" dùng cho đồ vật treo trên tường.',
    hints: ['Gợi ý 1: Treo trên tường dùng "on".', 'Gợi ý 2: on the wall.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q2-acl2-3',
    unitId: 'unit-2',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 2]\\nThe sofa is ________ the television and the lamp in the living room.',
    options: ['between', 'next to', 'under', 'behind'],
    correctAnswer: 'between',
    explanation: 'Cấu trúc "between A and B" chỉ vị trí ở giữa 2 vật.',
    hints: ['Gợi ý 1: Nhìn thấy từ "and".', 'Gợi ý 2: between... and...'],
    difficulty: 'Dễ'
  },
  {
    id: 'q2-acl2-4',
    unitId: 'unit-2',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 2]\\nMy ________ house is very big with a balcony and six rooms.',
    options: ["uncle's", 'uncles', 'uncle', "uncles's"],
    correctAnswer: "uncle's",
    explanation: "Sở hữu cách cho danh từ số ít 'uncle' là uncle's (Nhà của chú tôi).",
    hints: ["Gợi ý 1: Danh từ số ít thêm 's.", "Gợi ý 2: uncle's house."],
    difficulty: 'Dễ'
  },
  {
    id: 'q2-acl2-5',
    unitId: 'unit-2',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 2]\\nThe dog is sleeping ________ the table in the dining room.',
    options: ['under', 'on', 'between', 'above'],
    correctAnswer: 'under',
    explanation: 'Giới từ "under the table" nghĩa là nằm dưới gầm bàn.',
    hints: ['Gợi ý 1: Vị trí gầm bàn.', 'Gợi ý 2: "under" = bên dưới.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q2-acl2-6',
    unitId: 'unit-2',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 2]\\nThere is a big mirror ________ the sink in the bathroom.',
    options: ['above', 'under', 'between', 'in'],
    correctAnswer: 'above',
    explanation: 'Gương treo "above the sink" nghĩa là ở phía trên bồn rửa mặt.',
    hints: ['Gợi ý 1: Phía bên trên bồn rửa.', 'Gợi ý 2: "above" = ở phía trên.'],
    difficulty: 'Trung bình'
  },
  {
    id: 'q2-acl2-7',
    unitId: 'unit-2',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 2]\\nThese are my ________ books for the new school year.',
    options: ["sister's", 'sisters', 'sister', "sisters's"],
    correctAnswer: "sister's",
    explanation: "Sở hữu cách 'sister's books' (Sách của chị gái tôi).",
    hints: ["Gợi ý 1: Thêm 's vào danh từ sister.", "Gợi ý 2: sister's."],
    difficulty: 'Dễ'
  },
  {
    id: 'q2-acl2-8',
    unitId: 'unit-2',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 2]\\nThe garden is ________ the house, near the main entrance door.',
    options: ['in front of', 'between', 'under', 'on'],
    correctAnswer: 'in front of',
    explanation: '"in front of the house" = phía trước ngôi nhà.',
    hints: ['Gợi ý 1: Phía trước cổng chính.', 'Gợi ý 2: in front of.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q2-acl2-9',
    unitId: 'unit-2',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 2]\\nThe fridge is placed ________ the kitchen cabinet.',
    options: ['next to', 'between', 'under', 'on'],
    correctAnswer: 'next to',
    explanation: '"next to" nghĩa là ở bên cạnh tủ bếp.',
    hints: ['Gợi ý 1: Ở bên cạnh.', 'Gợi ý 2: next to.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q2-acl2-10',
    unitId: 'unit-2',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 2]\\nIs this ________ coat? - No, it belongs to Nam.',
    options: ["Phong's", 'Phong', 'Phongs', "Phong is"],
    correctAnswer: "Phong's",
    explanation: "Sở hữu cách: Phong's coat (Áo khoác của Phong).",
    hints: ["Gợi ý 1: Phong + 's.", "Gợi ý 2: Phong's."],
    difficulty: 'Dễ'
  },

  // ================= UNIT 3: MY FRIENDS (A Closer Look 2: Present Continuous) =================
  {
    id: 'q3-acl2-1',
    unitId: 'unit-3',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 3]\\nLook! My classmates ________ a picnic on the grass.',
    options: ['are having', 'have', 'has', 'having'],
    correctAnswer: 'are having',
    explanation: 'Dấu hiệu "Look!" chia thì Hiện tại tiếp diễn: S + am/is/are + V-ing. "My classmates" số nhiều đi với "are having".',
    hints: ['Gợi ý 1: "Look!" chỉ hành động đang diễn ra.', 'Gợi ý 2: S (số nhiều) + are + V-ing.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q3-acl2-2',
    unitId: 'unit-3',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 3]\\nListen! The music teacher ________ a song in the auditorium.',
    options: ['is singing', 'sings', 'sing', 'sung'],
    correctAnswer: 'is singing',
    explanation: 'Dấu hiệu "Listen!" chia Hiện tại tiếp diễn với "is singing".',
    hints: ['Gợi ý 1: "Listen!" = Hãy lắng nghe.', 'Gợi ý 2: is singing.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q3-acl2-3',
    unitId: 'unit-3',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 3]\\nWhat ________ Nam ________ right now? - He is playing chess.',
    options: ['is / doing', 'does / do', 'are / doing', 'do / do'],
    correctAnswer: 'is / doing',
    explanation: 'Dấu hiệu "right now" với chủ ngữ số ít "Nam": What + is + Nam + doing?',
    hints: ['Gợi ý 1: "right now" = ngay bây giờ.', 'Gợi ý 2: Nam đi với "is".'],
    difficulty: 'Dễ'
  },
  {
    id: 'q3-acl2-4',
    unitId: 'unit-3',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 3]\\nThey ________ not watching TV now; they are doing homework.',
    options: ['are', 'do', 'is', 'did'],
    correctAnswer: 'are',
    explanation: 'Phủ định hiện tại tiếp diễn: They + are + not + V-ing.',
    hints: ['Gợi ý 1: "They" đi với tobe "are".', 'Gợi ý 2: They are not.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q3-acl2-5',
    unitId: 'unit-3',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 3]\\nBe quiet! The baby ________ in her crib.',
    options: ['is sleeping', 'sleeps', 'sleep', 'slept'],
    correctAnswer: 'is sleeping',
    explanation: '"Be quiet!" -> Thì hiện tại tiếp diễn "is sleeping".',
    hints: ['Gợi ý 1: Cảnh báo hãy trật tự.', 'Gợi ý 2: is sleeping.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q3-acl2-6',
    unitId: 'unit-3',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 3]\\nAt the moment, Mai ________ a letter to her pen friend in London.',
    options: ['is writing', 'writes', 'write', 'wrote'],
    correctAnswer: 'is writing',
    explanation: 'Dấu hiệu "At the moment" chia "is writing".',
    hints: ['Gợi ý 1: "At the moment" = lúc này.', 'Gợi ý 2: is writing.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q3-acl2-7',
    unitId: 'unit-3',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 3]\\nWhy ________ you ________ your jacket inside the warm house?',
    options: ['are / wearing', 'do / wear', 'is / wearing', 'did / wear'],
    correctAnswer: 'are / wearing',
    explanation: 'Hỏi về hành động mặc áo khoác lúc này: Why + are + you + wearing?',
    hints: ['Gợi ý 1: Hành động đang xảy ra với "you".', 'Gợi ý 2: are you wearing.'],
    difficulty: 'Trung bình'
  },
  {
    id: 'q3-acl2-8',
    unitId: 'unit-3',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 3]\\nPhong and Duy ________ basketball in the sports center today.',
    options: ['are playing', 'play', 'plays', 'played'],
    correctAnswer: 'are playing',
    explanation: 'Hành động diễn ra hôm nay "today" dùng "are playing".',
    hints: ['Gợi ý 1: Chủ ngữ Phong and Duy là số nhiều.', 'Gợi ý 2: are playing.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q3-acl2-9',
    unitId: 'unit-3',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 3]\\nLook at the clouds! It ________ to rain very soon.',
    options: ['is starting', 'starts', 'started', 'start'],
    correctAnswer: 'is starting',
    explanation: 'Hành động nhìn thấy mây đen đang sắp mưa -> "is starting".',
    hints: ['Gợi ý 1: Look at...! chỉ việc đang xảy ra.', 'Gợi ý 2: is starting.'],
    difficulty: 'Trung bình'
  },
  {
    id: 'q3-acl2-10',
    unitId: 'unit-3',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 3]\\nShe ________ for her glasses right now because she lost them.',
    options: ['is looking', 'looks', 'looked', 'look'],
    correctAnswer: 'is looking',
    explanation: 'Dấu hiệu "right now" -> "is looking".',
    hints: ['Gợi ý 1: right now.', 'Gợi ý 2: is looking.'],
    difficulty: 'Dễ'
  },

  // ================= UNIT 4: MY NEIGHBOURHOOD (A Closer Look 2: Comparatives) =================
  {
    id: 'q4-acl2-1',
    unitId: 'unit-4',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 4]\\nThis street is ________ than that one near the market.',
    options: ['wider', 'more wide', 'widest', 'wide'],
    correctAnswer: 'wider',
    explanation: 'Tính từ ngắn "wide" chỉ cần thêm "-r" trong so sánh hơn -> "wider".',
    hints: ['Gợi ý 1: Tính từ "wide" đã có chữ "e".', 'Gợi ý 2: wider than.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q4-acl2-2',
    unitId: 'unit-4',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 4]\\nLife in the countryside is ________ than in big cities.',
    options: ['more peaceful', 'peacefuler', 'peaceful', 'most peaceful'],
    correctAnswer: 'more peaceful',
    explanation: 'Tính từ dài "peaceful" dùng "more peaceful than".',
    hints: ['Gợi ý 1: "peaceful" là tính từ 2 âm tiết.', 'Gợi ý 2: more peaceful.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q4-acl2-3',
    unitId: 'unit-4',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 4]\\nThe air in the mountain area is ________ than in the industrial park.',
    options: ['fresher', 'more fresh', 'freshest', 'fresh'],
    correctAnswer: 'fresher',
    explanation: 'Tính từ ngắn "fresh" -> "fresher".',
    hints: ['Gợi ý 1: "fresh" là tính từ 1 âm tiết.', 'Gợi ý 2: fresher.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q4-acl2-4',
    unitId: 'unit-4',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 4]\\nThe supermarket is ________ than the small corner shop.',
    options: ['more convenient', 'convenienter', 'convenient', 'most convenient'],
    correctAnswer: 'more convenient',
    explanation: 'Tính từ dài "convenient" -> "more convenient".',
    hints: ['Gợi ý 1: "convenient" là tính từ dài.', 'Gợi ý 2: more convenient.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q4-acl2-5',
    unitId: 'unit-4',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 4]\\nHotels in Paris are ________ than those in Hanoi.',
    options: ['more expensive', 'expensiver', 'expensive', 'most expensive'],
    correctAnswer: 'more expensive',
    explanation: 'Tính từ dài "expensive" -> "more expensive".',
    hints: ['Gợi ý 1: "expensive" 3 âm tiết.', 'Gợi ý 2: more expensive.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q4-acl2-6',
    unitId: 'unit-4',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 4]\\nThe weather today is ________ than yesterday.',
    options: ['hotter', 'more hot', 'hottest', 'hot'],
    correctAnswer: 'hotter',
    explanation: 'Tính từ "hot" gấp đôi phụ âm cuối trước khi thêm "-er" -> "hotter".',
    hints: ['Gợi ý 1: "hot" có 1 nguyên âm đứng giữa 2 phụ âm.', 'Gợi ý 2: Gấp đôi chữ t -> hotter.'],
    difficulty: 'Trung bình'
  },
  {
    id: 'q4-acl2-7',
    unitId: 'unit-4',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 4]\\nMy neighbourhood is ________ than yours; there are fewer vehicles.',
    options: ['quieter', 'more quiet', 'quietest', 'quiet'],
    correctAnswer: 'quieter',
    explanation: 'Tính từ "quiet" dùng dạng so sánh hơn "quieter".',
    hints: ['Gợi ý 1: "quiet" -> "quieter".', 'Gợi ý 2: quieter than.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q4-acl2-8',
    unitId: 'unit-4',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 4]\\nThis museum is ________ than the old cathedral.',
    options: ['more modern', 'moderner', 'modern', 'most modern'],
    correctAnswer: 'more modern',
    explanation: 'Tính từ dài "modern" -> "more modern".',
    hints: ['Gợi ý 1: "modern" dùng với "more".', 'Gợi ý 2: more modern.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q4-acl2-9',
    unitId: 'unit-4',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 4]\\nThe central square is ________ than the narrow alley.',
    options: ['busier', 'more busy', 'busiest', 'busy'],
    correctAnswer: 'busier',
    explanation: '"busy" -> đổi "y" thành "i" rồi thêm "-er" thành "busier".',
    hints: ['Gợi ý 1: Đuôi -y đổi thành -ier.', 'Gợi ý 2: busier.'],
    difficulty: 'Trung bình'
  },
  {
    id: 'q4-acl2-10',
    unitId: 'unit-4',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 4]\\nTraveling by bus is ________ than taking a taxi.',
    options: ['cheaper', 'more cheap', 'cheapest', 'cheap'],
    correctAnswer: 'cheaper',
    explanation: 'Tính từ ngắn "cheap" -> "cheaper".',
    hints: ['Gợi ý 1: "cheap" + er.', 'Gợi ý 2: cheaper.'],
    difficulty: 'Dễ'
  },

  // ================= UNIT 5: NATURAL WONDERS (A Closer Look 2: Countable/Uncountable & Must/Mustn't) =================
  {
    id: 'q5-acl2-1',
    unitId: 'unit-5',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 5]\\nYou ________ drop litter in the national park. It damages the environment!',
    options: ["mustn't", 'must', 'can', 'should'],
    correctAnswer: "mustn't",
    explanation: 'Hành vi cấm vứt rác gây tổn hại môi trường dùng "mustn\'t".',
    hints: ['Gợi ý 1: Hành vi cấm làm.', 'Gợi ý 2: mustn\'t.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q5-acl2-2',
    unitId: 'unit-5',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 5]\\nVisitors ________ wear warm clothes when visiting Mount Fansipan in winter.',
    options: ['must', "mustn't", "can't", "wouldn't"],
    correctAnswer: 'must',
    explanation: 'Việc cần thiết phải mặc ấm khi lên đỉnh núi tuyết lạnh -> "must".',
    hints: ['Gợi ý 1: Cần thiết phải làm.', 'Gợi ý 2: must.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q5-acl2-3',
    unitId: 'unit-5',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 5]\\nHow ________ fresh water do we need for the 3-day camping trip?',
    options: ['much', 'many', 'some', 'any'],
    correctAnswer: 'much',
    explanation: '"water" là danh từ không đếm được -> Dùng "How much".',
    hints: ['Gợi ý 1: Danh từ nước (water) không đếm được.', 'Gợi ý 2: How much.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q5-acl2-4',
    unitId: 'unit-5',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 5]\\nHow ________ plaster rolls are left in the medical kit?',
    options: ['many', 'much', 'some', 'a little'],
    correctAnswer: 'many',
    explanation: '"plaster rolls" (cuộn băng gạc) là danh từ số nhiều đếm được -> "How many".',
    hints: ['Gợi ý 1: Cuộn băng gạc đếm được.', 'Gợi ý 2: How many.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q5-acl2-5',
    unitId: 'unit-5',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 5]\\nYou ________ swim in this river; the current is very strong and dangerous.',
    options: ["mustn't", 'must', 'should', 'can'],
    correctAnswer: "mustn't",
    explanation: 'Dòng nước siết nguy hiểm -> Cấm bơi "mustn\'t".',
    hints: ['Gợi ý 1: Nguy hiểm cấm bơi.', 'Gợi ý 2: mustn\'t.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q5-acl2-6',
    unitId: 'unit-5',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 5]\\nWe need ________ suncream to protect our skin on the sunny beach.',
    options: ['some', 'any', 'many', 'few'],
    correctAnswer: 'some',
    explanation: 'Câu khẳng định dùng "some" trước danh từ không đếm được "suncream".',
    hints: ['Gợi ý 1: Câu khẳng định.', 'Gợi ý 2: some suncream.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q5-acl2-7',
    unitId: 'unit-5',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 5]\\nYou ________ bring a compass when exploring the deep forest.',
    options: ['must', "mustn't", "can't", "shouldn't"],
    correctAnswer: 'must',
    explanation: 'Bắt buộc mang theo la bàn để tránh lạc trong rừng sâu -> "must".',
    hints: ['Gợi ý 1: Bắt buộc để không bị lạc.', 'Gợi ý 2: must.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q5-acl2-8',
    unitId: 'unit-5',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 5]\\nAre there ________ sleeping bags in the storage tent?',
    options: ['any', 'some', 'much', 'a little'],
    correctAnswer: 'any',
    explanation: 'Câu hỏi Yes/No dùng "any" trước danh từ đếm được số nhiều.',
    hints: ['Gợi ý 1: Câu hỏi dùng "any".', 'Gợi ý 2: any.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q5-acl2-9',
    unitId: 'unit-5',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 5]\\nYou ________ make campfires in dry pine forests without permission.',
    options: ["mustn't", 'must', 'can', 'should'],
    correctAnswer: "mustn't",
    explanation: 'Cấm đốt lửa trại trong rừng thông khô -> "mustn\'t".',
    hints: ['Gợi ý 1: Hành vi nghiêm cấm.', 'Gợi ý 2: mustn\'t.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q5-acl2-10',
    unitId: 'unit-5',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 5]\\nHow ________ luggage can we carry on the boat tour?',
    options: ['much', 'many', 'some', 'few'],
    correctAnswer: 'much',
    explanation: '"luggage" (hành lý) là danh từ không đếm được -> "How much".',
    hints: ['Gợi ý 1: "luggage" không đếm được.', 'Gợi ý 2: How much luggage.'],
    difficulty: 'Trung bình'
  },

  // ================= UNIT 6: OUR TET HOLIDAY (A Closer Look 2: Should / Shouldn't & Some / Any) =================
  {
    id: 'q6-acl2-1',
    unitId: 'unit-6',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: "📌 [A CLOSER LOOK 2 - UNIT 6]\\nChildren ________ ask for lucky money greedily during Tet visits.",
    options: ["shouldn't", 'should', 'must', 'can'],
    correctAnswer: "shouldn't",
    explanation: 'Khuyên trẻ em không nên đòi tiền mừng tuổi một cách tham lam -> "shouldn\'t".',
    hints: ['Gợi ý 1: Lời khuyên không nên.', 'Gợi ý 2: shouldn\'t.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q6-acl2-2',
    unitId: 'unit-6',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 6]\\nWe ________ help clean and decorate our house before New Year.',
    options: ['should', "shouldn't", "mustn't", "couldn't"],
    correctAnswer: 'should',
    explanation: 'Nên giúp bố mẹ trang trí dọn dẹp nhà dịp Tết -> "should".',
    hints: ['Gợi ý 1: Lời khuyên nên làm.', 'Gợi ý 2: should.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q6-acl2-3',
    unitId: 'unit-6',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 6]\\nDo you have ________ peach blossom trees in your garden?',
    options: ['any', 'some', 'much', 'a little'],
    correctAnswer: 'any',
    explanation: 'Câu hỏi nghi vấn dùng "any" trước danh từ số nhiều.',
    hints: ['Gợi ý 1: Câu hỏi dùng "any".', 'Gợi ý 2: any.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q6-acl2-4',
    unitId: 'unit-6',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 6]\\nMy grandmother made ________ banh chung for our family gathering.',
    options: ['some', 'any', 'much', 'a'],
    correctAnswer: 'some',
    explanation: 'Câu khẳng định dùng "some banh chung".',
    hints: ['Gợi ý 1: Câu khẳng định.', 'Gợi ý 2: some.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q6-acl2-5',
    unitId: 'unit-6',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 6]\\nYou ________ sweep the floor on the first day of Tet.',
    options: ["shouldn't", 'should', 'must', 'can'],
    correctAnswer: "shouldn't",
    explanation: 'Theo phong tục không nên quét nhà ngày mùng 1 Tết -> "shouldn\'t".',
    hints: ['Gợi ý 1: Phong tục không nên làm.', 'Gợi ý 2: shouldn\'t.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q6-acl2-6',
    unitId: 'unit-6',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 6]\\nWe ________ wish our relatives happiness and good health in the New Year.',
    options: ['should', "shouldn't", "mustn't", "can't"],
    correctAnswer: 'should',
    explanation: 'Nên chúc Tết người thân -> "should".',
    hints: ['Gợi ý 1: Việc nên làm.', 'Gợi ý 2: should.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q6-acl2-7',
    unitId: 'unit-6',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 6]\\nIs there ________ red envelope left on the table?',
    options: ['any', 'some', 'many', 'few'],
    correctAnswer: 'any',
    explanation: 'Câu hỏi nghi vấn dùng "any".',
    hints: ['Gợi ý 1: Câu hỏi.', 'Gợi ý 2: any.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q6-acl2-8',
    unitId: 'unit-6',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 6]\\nPeople ________ stay up late every night during Tet to stay healthy.',
    options: ["shouldn't", 'should', 'must', 'could'],
    correctAnswer: "shouldn't",
    explanation: 'Không nên thức quá khuya -> "shouldn\'t".',
    hints: ['Gợi ý 1: Lời khuyên giữ sức khỏe.', 'Gợi ý 2: shouldn\'t.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q6-acl2-9',
    unitId: 'unit-6',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 6]\\nWe bought ________ fireworks to watch on New Year\'s Eve.',
    options: ['some', 'any', 'much', 'a little'],
    correctAnswer: 'some',
    explanation: 'Câu khẳng định dùng "some".',
    hints: ['Gợi ý 1: Câu khẳng định.', 'Gợi ý 2: some.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q6-acl2-10',
    unitId: 'unit-6',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 6]\\nYou ________ wear dark clothes on New Year\'s Day; wear bright ones instead.',
    options: ["shouldn't", 'should', 'must', 'can'],
    correctAnswer: "shouldn't",
    explanation: 'Khuyên không nên mặc đồ tối màu ngày Tết -> "shouldn\'t".',
    hints: ['Gợi ý 1: Nên mặc đồ sáng màu thay vì đồ tối.', 'Gợi ý 2: shouldn\'t.'],
    difficulty: 'Dễ'
  },

  // ================= UNIT 7: TELEVISION (A Closer Look 2: Wh-Questions & Conjunctions) =================
  {
    id: 'q7-acl2-1',
    unitId: 'unit-7',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 7]\\n________ is your favourite game show host? - It is Mr. Lai Van Sam.',
    options: ['Who', 'What', 'Where', 'When'],
    correctAnswer: 'Who',
    explanation: 'Hỏi về người (MC dẫn chương trình) dùng "Who".',
    hints: ['Gợi ý 1: Hỏi về người.', 'Gợi ý 2: Who.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q7-acl2-2',
    unitId: 'unit-7',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 7]\\nThe cartoon is funny, ________ I watch it every evening.',
    options: ['so', 'because', 'but', 'or'],
    correctAnswer: 'so',
    explanation: 'Mệnh đề kết quả (phim hài hước NÊN tôi xem mỗi tối) dùng "so".',
    hints: ['Gợi ý 1: Mệnh đề chỉ kết quả.', 'Gợi ý 2: so = vì thế.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q7-acl2-3',
    unitId: 'unit-7',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 7]\\n________ do you usually watch TV? - In the living room.',
    options: ['Where', 'When', 'Why', 'What'],
    correctAnswer: 'Where',
    explanation: 'Hỏi về địa điểm (In the living room) dùng "Where".',
    hints: ['Gợi ý 1: Hỏi về vị trí / địa điểm.', 'Gợi ý 2: Where.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q7-acl2-4',
    unitId: 'unit-7',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 7]\\nI want to watch the football match, ________ I must finish my homework first.',
    options: ['but', 'so', 'because', 'and'],
    correctAnswer: 'but',
    explanation: 'Mệnh đề thể hiện sự đối lập (Muốn xem NHƯNG phải làm bài trước) dùng "but".',
    hints: ['Gợi ý 1: Sự đối lập.', 'Gợi ý 2: but = nhưng.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q7-acl2-5',
    unitId: 'unit-7',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 7]\\n________ do you watch the educational program? - At 8 p.m on Saturdays.',
    options: ['When', 'Where', 'Why', 'Who'],
    correctAnswer: 'When',
    explanation: 'Hỏi về thời gian (At 8 p.m) dùng từ hỏi "When".',
    hints: ['Gợi ý 1: Hỏi thời gian.', 'Gợi ý 2: When.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q7-acl2-6',
    unitId: 'unit-7',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 7]\\nHe turned off the TV ________ he wanted to go to bed early.',
    options: ['because', 'so', 'but', 'and'],
    correctAnswer: 'because',
    explanation: 'Mệnh đề chỉ nguyên nhân (BỞI VÌ muốn ngủ sớm) dùng "because".',
    hints: ['Gợi ý 1: Nguyên nhân.', 'Gợi ý 2: because.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q7-acl2-7',
    unitId: 'unit-7',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 7]\\n________ is the title of the documentary film? - It is "The Green Planet".',
    options: ['What', 'Who', 'Where', 'Why'],
    correctAnswer: 'What',
    explanation: 'Hỏi về tiêu đề bộ phim dùng từ hỏi "What".',
    hints: ['Gợi ý 1: Hỏi cái gì / tiêu đề gì.', 'Gợi ý 2: What.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q7-acl2-8',
    unitId: 'unit-7',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 7]\\nThe game show is exciting ________ educational for Grade 6 students.',
    options: ['and', 'but', 'so', 'because'],
    correctAnswer: 'and',
    explanation: 'Bổ sung thêm 2 tính từ tích cực (vừa hấp dẫn VÀ vừa có tính giáo dục) dùng "and".',
    hints: ['Gợi ý 1: Nối 2 tính từ cùng chiều.', 'Gợi ý 2: and.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q7-acl2-9',
    unitId: 'unit-7',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 7]\\n________ do children love watching Tom and Jerry? - Because it makes them laugh.',
    options: ['Why', 'What', 'When', 'Where'],
    correctAnswer: 'Why',
    explanation: 'Trả lời nguyên nhân bởi vì (Because...) -> Từ hỏi là "Why".',
    hints: ['Gợi ý 1: Hỏi lý do.', 'Gợi ý 2: Why.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q7-acl2-10',
    unitId: 'unit-7',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 7]\\nShe missed the talent show ________ her laptop ran out of battery.',
    options: ['because', 'so', 'but', 'and'],
    correctAnswer: 'because',
    explanation: 'Mệnh đề nguyên nhân dùng "because".',
    hints: ['Gợi ý 1: Chỉ lý do hết pin.', 'Gợi ý 2: because.'],
    difficulty: 'Dễ'
  },

  // ================= UNIT 8: SPORTS AND GAMES (A Closer Look 2: Past Simple & Imperatives) =================
  {
    id: 'q8-acl2-1',
    unitId: 'unit-8',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 8]\\nLast Sunday, my brother ________ the first prize in the chess competition.',
    options: ['won', 'win', 'wins', 'winning'],
    correctAnswer: 'won',
    explanation: 'Dấu hiệu "Last Sunday" chia thì Quá khứ đơn của động từ bất quy tắc win -> "won".',
    hints: ['Gợi ý 1: "Last Sunday" chỉ thời quá khứ.', 'Gợi ý 2: win -> won.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q8-acl2-2',
    unitId: 'unit-8',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 8]\\n________ your sports shoes before entering the badminton court!',
    options: ['Put on', 'Putting on', 'Putted on', 'Puts on'],
    correctAnswer: 'Put on',
    explanation: 'Câu mệnh lệnh khẳng định bắt đầu bằng động từ nguyên mẫu: "Put on...!".',
    hints: ['Gợi ý 1: Mệnh lệnh bắt đầu bằng động từ nguyên mẫu.', 'Gợi ý 2: Put on.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q8-acl2-3',
    unitId: 'unit-8',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 8]\\nWe ________ a great swimming lesson yesterday afternoon.',
    options: ['had', 'have', 'has', 'having'],
    correctAnswer: 'had',
    explanation: 'Dấu hiệu "yesterday afternoon" chia quá khứ đơn of have -> "had".',
    hints: ['Gợi ý 1: Quá khứ của have.', 'Gợi ý 2: had.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q8-acl2-4',
    unitId: 'unit-8',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 8]\\nDon\'t ________ fast on the wet playground! You might fall.',
    options: ['run', 'running', 'ran', 'runs'],
    correctAnswer: 'run',
    explanation: 'Mệnh lệnh phủ định: Don\'t + V_inf -> "Don\'t run".',
    hints: ['Gợi ý 1: Don\'t + động từ nguyên mẫu.', 'Gợi ý 2: run.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q8-acl2-5',
    unitId: 'unit-8',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 8]\\nPhong ________ a new pair of goggles for swimming last Saturday.',
    options: ['bought', 'buy', 'buys', 'buying'],
    correctAnswer: 'bought',
    explanation: 'Quá khứ của buy (last Saturday) -> "bought".',
    hints: ['Gợi ý 1: buy -> bought.', 'Gợi ý 2: bought.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q8-acl2-6',
    unitId: 'unit-8',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 8]\\n________ warm-up exercises carefully before running the marathon!',
    options: ['Do', 'Doing', 'Did', 'Done'],
    correctAnswer: 'Do',
    explanation: 'Câu mệnh lệnh bắt đầu bằng động từ nguyên mẫu "Do".',
    hints: ['Gợi ý 1: Động từ nguyên mẫu đầu câu mệnh lệnh.', 'Gợi ý 2: Do.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q8-acl2-7',
    unitId: 'unit-8',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 8]\\n________ you see the basketball match on TV last night?',
    options: ['Did', 'Do', 'Are', 'Were'],
    correctAnswer: 'Did',
    explanation: 'Trợ động từ quá khứ đơn trong câu hỏi nghi vấn là "Did".',
    hints: ['Gợi ý 1: "last night" thời quá khứ.', 'Gợi ý 2: Did + S + V?'],
    difficulty: 'Dễ'
  },
  {
    id: 'q8-acl2-8',
    unitId: 'unit-8',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 8]\\nDon\'t ________ late for physical education class tomorrow!',
    options: ['be', 'is', 'are', 'was'],
    correctAnswer: 'be',
    explanation: 'Mệnh lệnh phủ định với tính từ: Don\'t + be + adj.',
    hints: ['Gợi ý 1: Don\'t be late.', 'Gợi ý 2: be.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q8-acl2-9',
    unitId: 'unit-8',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 8]\\nMy team ________ win the karate match two days ago.',
    options: ["didn't", "doesn't", "isn't", "wasn't"],
    correctAnswer: "didn't",
    explanation: 'Trợ động từ phủ định quá khứ đơn "didn\'t + V_inf".',
    hints: ['Gợi ý 1: "two days ago" thời quá khứ.', 'Gợi ý 2: didn\'t.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q8-acl2-10',
    unitId: 'unit-8',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 8]\\n________ quiet when the referee is talking!',
    options: ['Keep', 'Keeping', 'Kept', 'Keeps'],
    correctAnswer: 'Keep',
    explanation: 'Mệnh lệnh "Keep quiet!" (Hãy giữ trật tự!).',
    hints: ['Gợi ý 1: Mệnh lệnh khẳng định.', 'Gợi ý 2: Keep.'],
    difficulty: 'Dễ'
  },

  // ================= UNIT 9: CITIES OF THE WORLD (A Closer Look 2: Possessives & Superlatives) =================
  {
    id: 'q9-acl2-1',
    unitId: 'unit-9',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 9]\\nThis travel map is mine, and that camera is ________.',
    options: ['yours', 'your', 'you', "yours'"],
    correctAnswer: 'yours',
    explanation: 'Đại từ sở hữu "yours" đứng ở cuối câu thay cho "your camera".',
    hints: ['Gợi ý 1: Đại từ sở hữu.', 'Gợi ý 2: yours.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q9-acl2-2',
    unitId: 'unit-9',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 9]\\nLondon is the ________ historic city I have ever visited.',
    options: ['most famous', 'famousest', 'more famous', 'famous'],
    correctAnswer: 'most famous',
    explanation: 'So sánh nhất tính từ dài "the most famous".',
    hints: ['Gợi ý 1: Có mạo từ "the".', 'Gợi ý 2: the most famous.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q9-acl2-3',
    unitId: 'unit-9',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 9]\\nIs this red suitcase ________ or hers?',
    options: ['his', 'he', 'him', "he's"],
    correctAnswer: 'his',
    explanation: 'Đại từ sở hữu "his" song song với "hers".',
    hints: ['Gợi ý 1: Đại từ sở hữu của he.', 'Gợi ý 2: his.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q9-acl2-4',
    unitId: 'unit-9',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 9]\\nTokyo is one of the ________ cities in Asia.',
    options: ['cleanest', 'cleaner', 'most clean', 'clean'],
    correctAnswer: 'cleanest',
    explanation: 'So sánh nhất tính từ ngắn "clean" -> "the cleanest".',
    hints: ['Gợi ý 1: "clean" là tính từ ngắn.', 'Gợi ý 2: the cleanest.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q9-acl2-5',
    unitId: 'unit-9',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 9]\\nOur postcard arrived today, but ________ hasn\'t arrived yet.',
    options: ['theirs', 'their', 'they', 'them'],
    correctAnswer: 'theirs',
    explanation: 'Đại từ sở hữu "theirs" làm chủ ngữ thay cho "their postcard".',
    hints: ['Gợi ý 1: Đại từ sở hữu thay thế cho their postcard.', 'Gợi ý 2: theirs.'],
    difficulty: 'Trung bình'
  },
  {
    id: 'q9-acl2-6',
    unitId: 'unit-9',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 9]\\nWhat is the ________ skyscraper in Southeast Asia?',
    options: ['tallest', 'most tall', 'taller', 'tall'],
    correctAnswer: 'tallest',
    explanation: 'So sánh nhất tính từ ngắn "tall" -> "the tallest".',
    hints: ['Gợi ý 1: tall + est.', 'Gợi ý 2: tallest.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q9-acl2-7',
    unitId: 'unit-9',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 9]\\nMy hotel room has a city view, but ________ has a sea view.',
    options: ['hers', 'her', 'she', "hers'"],
    correctAnswer: 'hers',
    explanation: 'Đại từ sở hữu "hers" thay thế cho "her hotel room".',
    hints: ['Gợi ý 1: Đại từ sở hữu của she.', 'Gợi ý 2: hers.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q9-acl2-8',
    unitId: 'unit-9',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 9]\\nMount Everest is the ________ mountain on Earth.',
    options: ['highest', 'higher', 'most high', 'high'],
    correctAnswer: 'highest',
    explanation: 'So sánh nhất "the highest".',
    hints: ['Gợi ý 1: high + est.', 'Gợi ý 2: highest.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q9-acl2-9',
    unitId: 'unit-9',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 9]\\nYour passport is in your bag, but where is ________?',
    options: ['mine', 'my', 'I', 'me'],
    correctAnswer: 'mine',
    explanation: 'Đại từ sở hữu "mine" thay thế cho "my passport".',
    hints: ['Gợi ý 1: Đại từ sở hữu của I.', 'Gợi ý 2: mine.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q9-acl2-10',
    unitId: 'unit-9',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 9]\\nHa Long Bay is one of the ________ natural attractions in Vietnam.',
    options: ['most popular', 'popularer', 'popular', 'more popular'],
    correctAnswer: 'most popular',
    explanation: 'So sánh nhất "the most popular".',
    hints: ['Gợi ý 1: popular 3 âm tiết.', 'Gợi ý 2: most popular.'],
    difficulty: 'Dễ'
  },

  // ================= UNIT 10: OUR HOUSES IN THE FUTURE (A Closer Look 2: Will & Might) =================
  {
    id: 'q10-acl2-1',
    unitId: 'unit-10',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 10]\\nIn 2050, smart home robots ________ clean all rooms automatically.',
    options: ['will', 'did', 'are', 'were'],
    correctAnswer: 'will',
    explanation: 'Dự đoán tương lai chắc chắn dùng "will".',
    hints: ['Gợi ý 1: Mốc thời gian tương lai 2050.', 'Gợi ý 2: will.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q10-acl2-2',
    unitId: 'unit-10',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 10]\\nWe ________ live in floating houses if sea levels rise in the future.',
    options: ['might', 'must', 'should', "can't"],
    correctAnswer: 'might',
    explanation: 'Diễn tả khả năng tương lai có thể xảy ra dùng "might".',
    hints: ['Gợi ý 1: Khả năng tương lai không chắc chắn 100%.', 'Gợi ý 2: might.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q10-acl2-3',
    unitId: 'unit-10',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 10]\\nSolar panels on roof ________ produce clean electricity for our house.',
    options: ['will', "won't", 'did', "didn't"],
    correctAnswer: 'will',
    explanation: 'Dự đoán tương lai khẳng định "will produce".',
    hints: ['Gợi ý 1: will + V.', 'Gợi ý 2: will.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q10-acl2-4',
    unitId: 'unit-10',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 10]\\nI am not sure, but we ________ travel to Mars for summer vacation.',
    options: ['might', 'will', 'must', 'should'],
    correctAnswer: 'might',
    explanation: 'Cụm "not sure" đi với "might".',
    hints: ['Gợi ý 1: "not sure" = chưa chắc chắn.', 'Gợi ý 2: might.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q10-acl2-5',
    unitId: 'unit-10',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 10]\\nFuture houses ________ not use traditional coal energy.',
    options: ['will', 'do', 'are', 'have'],
    correctAnswer: 'will',
    explanation: 'Dạng phủ định "will not use".',
    hints: ['Gợi ý 1: will not use.', 'Gợi ý 2: will.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q10-acl2-6',
    unitId: 'unit-10',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 10]\\nSmart fridges ________ order food online when it runs out.',
    options: ['will', 'did', 'were', 'are'],
    correctAnswer: 'will',
    explanation: 'Tương lai đơn "will order".',
    hints: ['Gợi ý 1: Dự đoán thiết bị thông minh tương lai.', 'Gợi ý 2: will.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q10-acl2-7',
    unitId: 'unit-10',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 10]\\nHi-tech robots ________ replace human workers in dangerous places.',
    options: ['will', 'did', 'are', 'were'],
    correctAnswer: 'will',
    explanation: 'Dự đoán tương lai "will replace".',
    hints: ['Gợi ý 1: Tương lai đơn.', 'Gợi ý 2: will.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q10-acl2-8',
    unitId: 'unit-10',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 10]\\nTake an umbrella! It ________ rain later in the evening.',
    options: ['might', 'will not', "mustn't", "shouldn't"],
    correctAnswer: 'might',
    explanation: 'Khả năng thời tiết có thể mưa "might".',
    hints: ['Gợi ý 1: Khả năng thời tiết.', 'Gợi ý 2: might.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q10-acl2-9',
    unitId: 'unit-10',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 10]\\nPeople ________ drive flying cars in 2080.',
    options: ['might', 'did', 'were', 'are'],
    correctAnswer: 'might',
    explanation: 'Khả năng tương lai "might".',
    hints: ['Gợi ý 1: mốc thời gian 2080.', 'Gợi ý 2: might.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q10-acl2-10',
    unitId: 'unit-10',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 10]\\nAutomatic doors ________ open when you walk close to them.',
    options: ['will', 'did', 'were', 'are'],
    correctAnswer: 'will',
    explanation: 'Hành động của cửa tự động "will open".',
    hints: ['Gợi ý 1: will + V_inf.', 'Gợi ý 2: will.'],
    difficulty: 'Dễ'
  },

  // ================= UNIT 11: OUR GREENER WORLD (A Closer Look 2: First Conditional & Articles) =================
  {
    id: 'q11-acl2-1',
    unitId: 'unit-11',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 11]\\nIf students plant more trees, the air ________ cleaner.',
    options: ['will become', 'becomes', 'became', 'becoming'],
    correctAnswer: 'will become',
    explanation: 'Mệnh đề chính câu điều kiện loại 1: S + will + V_inf -> "will become".',
    hints: ['Gợi ý 1: Mệnh đề chính của câu điều kiện 1.', 'Gợi ý 2: will + V.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q11-acl2-2',
    unitId: 'unit-11',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 11]\\nLook at ________ Moon tonight! It is full and shining brightly.',
    options: ['the', 'a', 'an', 'x'],
    correctAnswer: 'the',
    explanation: 'Vật thể độc nhất vô nhị (Mặt trăng) dùng mạo từ "the".',
    hints: ['Gợi ý 1: Mặt trăng là vật thể duy nhất.', 'Gợi ý 2: the Moon.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q11-acl2-3',
    unitId: 'unit-11',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 11]\\nIf we ________ plastic bottles, we will protect the marine life.',
    options: ['recycle', 'will recycle', 'recycled', 'recycling'],
    correctAnswer: 'recycle',
    explanation: 'Mệnh đề If chia Hiện tại đơn: If + we + recycle.',
    hints: ['Gợi ý 1: Mệnh đề chứa If chia hiện tại đơn.', 'Gợi ý 2: recycle.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q11-acl2-4',
    unitId: 'unit-11',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 11]\\nOur 3Rs club member is ________ active student.',
    options: ['an', 'a', 'the', 'x'],
    correctAnswer: 'an',
    explanation: 'Từ "active" bắt đầu bằng nguyên âm "a" -> dùng "an".',
    hints: ['Gợi ý 1: Nguyên âm a.', 'Gợi ý 2: an active.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q11-acl2-5',
    unitId: 'unit-11',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 11]\\nIf you turn off the tap while brushing teeth, you ________ water.',
    options: ['will save', 'save', 'saved', 'are saving'],
    correctAnswer: 'will save',
    explanation: 'Mệnh đề chính điều kiện loại 1 dùng "will save".',
    hints: ['Gợi ý 1: will + V.', 'Gợi ý 2: will save.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q11-acl2-6',
    unitId: 'unit-11',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 11]\\nMy father works as ________ environmental officer.',
    options: ['an', 'a', 'the', 'x'],
    correctAnswer: 'an',
    explanation: 'Từ "environmental" bắt đầu bằng nguyên âm "e" -> "an".',
    hints: ['Gợi ý 1: Bắt đầu bằng âm e.', 'Gợi ý 2: an.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q11-acl2-7',
    unitId: 'unit-11',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 11]\\nIf people ________ reusable bags, plastic waste will decrease.',
    options: ['use', 'will use', 'used', 'using'],
    correctAnswer: 'use',
    explanation: 'Mệnh đề If chia hiện tại đơn "use".',
    hints: ['Gợi ý 1: If + S + V(pres).', 'Gợi ý 2: use.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q11-acl2-8',
    unitId: 'unit-11',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 11]\\n________ Sun is the main source of renewable energy on Earth.',
    options: ['The', 'A', 'An', 'X'],
    correctAnswer: 'The',
    explanation: 'Vật thể độc nhất "The Sun".',
    hints: ['Gợi ý 1: Mặt trời dùng The.', 'Gợi ý 2: The.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q11-acl2-9',
    unitId: 'unit-11',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 11]\\nIf we throw trash into rivers, fish ________ die.',
    options: ['will', 'did', 'are', 'were'],
    correctAnswer: 'will',
    explanation: 'Mệnh đề chính điều kiện 1: "will die".',
    hints: ['Gợi ý 1: will + V.', 'Gợi ý 2: will.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q11-acl2-10',
    unitId: 'unit-11',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 11]\\nWe should buy ________ reusable water bottle for daily use.',
    options: ['a', 'an', 'the', 'x'],
    correctAnswer: 'a',
    explanation: 'Từ "reusable" bắt đầu bằng phụ âm /r/ -> dùng "a".',
    hints: ['Gợi ý 1: Từ reusable bắt đầu bằng phụ âm.', 'Gợi ý 2: a.'],
    difficulty: 'Dễ'
  },

  // ================= UNIT 12: ROBOTS (A Closer Look 2: Superlatives & Could/Couldn't) =================
  {
    id: 'q12-acl2-1',
    unitId: 'unit-12',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 12]\\nShifa is the ________ doctor robot in our smart hospital.',
    options: ['smartest', 'smarter', 'smart', 'more smart'],
    correctAnswer: 'smartest',
    explanation: 'So sánh nhất "the smartest".',
    hints: ['Gợi ý 1: the + smart + est.', 'Gợi ý 2: smartest.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q12-acl2-2',
    unitId: 'unit-12',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 12]\\nWhen my grandfather was young, he ________ run very fast.',
    options: ['could', 'can', 'will', 'must'],
    correctAnswer: 'could',
    explanation: 'Khả năng trong quá khứ ("was young") -> "could".',
    hints: ['Gợi ý 1: Quá khứ của can là could.', 'Gợi ý 2: could.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q12-acl2-3',
    unitId: 'unit-12',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 12]\\nRoboMax is the ________ worker robot in the factory.',
    options: ['strongest', 'stronger', 'most strong', 'strong'],
    correctAnswer: 'strongest',
    explanation: 'So sánh nhất "the strongest".',
    hints: ['Gợi ý 1: strong + est.', 'Gợi ý 2: strongest.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q12-acl2-4',
    unitId: 'unit-12',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 12]\\nTen years ago, home robots ________ iron clothes automatically.',
    options: ["couldn't", "can't", "won't", "shouldn't"],
    correctAnswer: "couldn't",
    explanation: 'Không thể trong quá khứ ("Ten years ago") -> "couldn\'t".',
    hints: ['Gợi ý 1: Quá khứ của can\'t là couldn\'t.', 'Gợi ý 2: couldn\'t.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q12-acl2-5',
    unitId: 'unit-12',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 12]\\nWhen I was five years old, I ________ swim in deep water.',
    options: ["couldn't", "can't", "won't", "mustn't"],
    correctAnswer: "couldn't",
    explanation: 'Khả năng phủ định quá khứ lúc 5 tuổi -> "couldn\'t".',
    hints: ['Gợi ý 1: Thời quá khứ lúc 5 tuổi.', 'Gợi ý 2: couldn\'t.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q12-acl2-6',
    unitId: 'unit-12',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 12]\\nThis robot model can jump the ________ in the competition.',
    options: ['highest', 'higher', 'most high', 'high'],
    correctAnswer: 'highest',
    explanation: 'So sánh nhất "the highest".',
    hints: ['Gợi ý 1: high + est.', 'Gợi ý 2: highest.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q12-acl2-7',
    unitId: 'unit-12',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 12]\\nIn 1995, scientists ________ create AI robots with human voice recognition.',
    options: ["couldn't", "can't", "won't", "shouldn't"],
    correctAnswer: "couldn't",
    explanation: 'Mốc thời gian quá khứ 1995 -> "couldn\'t".',
    hints: ['Gợi ý 1: Mốc quá khứ 1995.', 'Gợi ý 2: couldn\'t.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q12-acl2-8',
    unitId: 'unit-12',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 12]\\nLast year, my brother ________ speak English fluently, but now he can.',
    options: ["couldn't", "can't", "won't", "shouldn't"],
    correctAnswer: "couldn't",
    explanation: 'Năm ngoái chưa thể -> "couldn\'t".',
    hints: ['Gợi ý 1: Dấu hiệu "Last year".', 'Gợi ý 2: couldn\'t.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q12-acl2-9',
    unitId: 'unit-12',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 12]\\nWhat is the ________ robot in the world exhibition?',
    options: ['fastest', 'faster', 'most fast', 'fast'],
    correctAnswer: 'fastest',
    explanation: 'So sánh nhất tính từ ngắn "fast" -> "the fastest".',
    hints: ['Gợi ý 1: fast + est.', 'Gợi ý 2: fastest.'],
    difficulty: 'Dễ'
  },
  {
    id: 'q12-acl2-10',
    unitId: 'unit-12',
    skill: 'Grammar',
    type: 'multiple-choice',
    content: '📌 [A CLOSER LOOK 2 - UNIT 12]\\nIn the 20th century, robots ________ perform surgical operations like today.',
    options: ["couldn't", "can't", "won't", "mustn't"],
    correctAnswer: "couldn't",
    explanation: 'Thế kỷ 20 trong quá khứ -> "couldn\'t".',
    hints: ['Gợi ý 1: Quá khứ ở thế kỷ 20.', 'Gợi ý 2: couldn\'t.'],
    difficulty: 'Dễ'
  }
];

const filePath = 'd:\\đảng viên\\2025\\Viet apps\\Englishtutor 6\\src\\data\\sgkData.ts';
let content = fs.readFileSync(filePath, 'utf8');

const tsItems = acl2Questions.map((q) => {
  const optsStr = q.options.map((opt) => `'${opt.replace(/'/g, "\\'")}'`).join(',\n      ');
  const hintsStr = q.hints.map((h) => `'${h.replace(/'/g, "\\'")}'`).join(',\n      ');
  return `  {
    id: '${q.id}',
    unitId: '${q.unitId}',
    skill: '${q.skill}',
    type: '${q.type}',
    content: '${q.content.replace(/'/g, "\\'")}',
    options: [
      ${optsStr}
    ],
    correctAnswer: '${q.correctAnswer.replace(/'/g, "\\'")}',
    explanation: '${q.explanation.replace(/'/g, "\\'")}',
    hints: [
      ${hintsStr}
    ],
    difficulty: '${q.difficulty}'
  }`;
});

const insertedTs = ',\n' + tsItems.join(',\n');
const targetRegex = /\r?\n\];\r?\n\r?\nexport const INITIAL_PROGRESS = {/;

if (targetRegex.test(content)) {
  const newContent = content.replace(targetRegex, `${insertedTs}\n];\n\nexport const INITIAL_PROGRESS = {`);
  fs.writeFileSync(filePath, newContent, 'utf8');
  console.log(`Successfully added ${acl2Questions.length} A CLOSER LOOK 2 questions to sgkData.ts!`);
} else {
  console.error('Target anchor not found in sgkData.ts');
}
